name: "Benchmark run (OpenRouter)"
description: "Request a benchmark run for a single OpenRouter model"
title: "Benchmark: <author>/<model> (OpenRouter)"
body:
  - type: markdown
    attributes:
      value: |
        Submit a benchmark request for a single OpenRouter model.

        - Only org members/collaborators can trigger runs.
        - A workflow will validate this issue when the `run-benchmark` label is applied.

  - type: textarea
    id: models
    attributes:
      label: Model (OpenRouter URL or slug)
      description: |
        Exactly one model. Accepted formats:
        - https://openrouter.ai/<author>/<model>
        - <author>/<model>
      placeholder: |
        https://openrouter.ai/mistralai/mistral-large-2512
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notes (optional)
      description: Any context for reviewers / maintainers.
    validations:
      required: false